version: '3'
services:
  db:
    image: mysql:latest
    container_name: mnsdb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: apirest

    ports:
      - "3308:3306"
    volumes:
      - dbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: mnsphpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    restart: always
    ports:
      - "8181:80"
    depends_on:
      - db

volumes:
  dbdata:
