version: '3'
services:
  db:
    image: mysql:latest
    container_name: mnsdb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: apirest
      MYSQL_USER: your-username
      MYSQL_PASSWORD: your-password
    ports:
      - "3308:3306"
    volumes:
      - dbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: mnsphpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    restart: always
    ports:
      - "8181:80"
    depends_on:
      - db

  app:
    image: mnsgarage
    container_name: mnsgarage_backend
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/apirest
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8080:8080"

volumes:
  dbdata:
