name: Construction d'un projet

on:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  create-folder:
    name: create-folder
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using key
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: mkdir -p /opt/applications/sa

  build:
    runs-on: ubuntu-latest
    needs: create-folder
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Telechargement des sources
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file
      - name: Build with Maven
        run: mvn -Dmaven.test.skip=true -B package --file pom.xml
      - name: Rename jar
        run: mv target/*.jar target/mnsgarage.jar
      - name: copy file via ssh key
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          source: "target/mnsgarage.jar"
          target: /opt/applications/sa

  run-script:
    name: run script
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: executing remote ssh commands using key
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            ln -sf /opt/applications/sa/mnsgarage.jar /etc/init.d/sa
            service sa start
